export const environment = {
  production: true,
  PROGRAM_ID: '6fRJuCgeW7MDxyuFTYGeCNyASxVZixgkfJBRFUZUF4sx',
  POOL_ADDRESS: '6KBL8pMWQh9yM96Zxda7r1DFH5sqMgkrwacUjKEVeDPb',
  SWAP_WS_URL: 'https://simplio-api-prod.azurewebsites.net/ws/notifications',
  SWAP_URL: 'https://simplio-prod.azurefd.net/api',
  SWAP_URL_DEX: 'https://dex-server.simplio.io/api',
  LANG_URL: 'https://files.simplio.io/prod/',
  TEMPLATE_REGISTRATION: 'SIO.REGISTRATION',
  TEMPLATE_RESET: 'SIO.PASSWORD-RESET',
  EXPLORER_URL: 'https://files.simplio.io/explorers_fallback.json',
  FEE_URL: 'https://files.simplio.io/feev2.json',
  POLICY_VERSION: '0.1.2',
  CORS_ANYWHERE: 'http://localhost:8080/',
  DATA: 'https://data.simplio.io/',
  POOLS_INFO: 'https://pools-info.simplio.io/',
  DATA_PASSWORD: 'TXID_PASSWORD123!',
  PIN_LENGTH: 4,
  DEFAULT_LANGUAGE: 'en',
  PREFIX: 'SIMPLIO',
  LIVECHAT_LICENCE_ID: 13126005,
  SUM_SUB_API_URL: 'https://api.sumsub.com',
  USER_API: 'https://simplio-8tkjnaqb.ew.gateway.dev',
  SWIPELUX: 'https://api.aws-dev.swipelux.com/api',
  SWIPELUX_NEW: 'https://jvm.api.aws-dev.swipelux.com/api',
};
