export const environment = {
  production: false,
  PROGRAM_ID: '6fRJuCgeW7MDxyuFTYGeCNyASxVZixgkfJBRFUZUF4sx',
  POOL_ADDRESS: '6KBL8pMWQh9yM96Zxda7r1DFH5sqMgkrwacUjKEVeDPb',
  SWAP_WS_URL: 'https://simplio-api-test.azurewebsites.net/ws/notifications',
  SWAP_URL: 'https://simplio-test.azurefd.net/api',
  LANG_URL: 'https://files.simplio.io/beta/',
  TEMPLATE_REGISTRATION: 'SIO.REGISTRATION',
  TEMPLATE_RESET: 'SIO.PASSWORD-RESET',
  EXPLORER_URL: 'https://files.simplio.io/explorers_fallback_beta.json',
  FEE_URL: 'https://files.simplio.io/feev2.json',
  POLICY_VERSION: '0.1.2',
  CORS_ANYWHERE: 'http://localhost:8080/',
  DATA: 'https://data.simplio.io/',
  POOLS_INFO: 'https://pools-info.simplio.io/',
  DATA_PASSWORD: 'TXID_PASSWORD123!',
  PIN_LENGTH: 4,
  DEFAULT_LANGUAGE: 'en',
  PREFIX: 'SIMPLIO_TEST',
  LIVECHAT_LICENCE_ID: 13126005,
  SUM_SUB_API_URL: 'https://test-api.sumsub.com',
  USER_API: 'https://simplio-test-8tkjnaqb.ew.gateway.dev',
  SWIPELUX: 'https://jvm.api.aws-dev.swipelux.com/api',
  CUSTOM_CONTENT: {
    SWIPELUX: true,
    STAKING: false,
  },
  appInsights: {
    instrumentationKey: 'fe4f6428-15d6-4336-9397-3c514e1030db',
  },
};
