export const environment = {
  production: true,
  POOL_ADDRESS: 'CQtV4WPQYUXDHxTXw8K6RJhqiFdndCSBVtj6vtbUoYjD',
  PROGRAM_ID: 'G7zRLf9JT5V1XJVRS2bNM7rKUvkpkw5ESGa52mfTpvGF',
  SWAP_WS_URL: 'https://simplio-api-prod.azurewebsites.net/ws/notifications',
  SWAP_URL: 'https://simplio-prod.azurefd.net/api',
  SWAP_URL_DEX: 'https://dex-server.simplio.io/api',
  LANG_URL: 'https://files.simplio.io/prod/',
  TEMPLATE_REGISTRATION: 'SIO.REGISTRATION',
  TEMPLATE_RESET: 'SIO.PASSWORD-RESET',
  EXPLORER_URL: 'https://files.simplio.io/explorers_fallback.json',
  FEE_URL: 'https://files.simplio.io/feev2.json',
  POLICY_VERSION: '0.1.2',
  CORS_ANYWHERE: 'http://localhost:8080/',
  DATA: 'https://data.simplio.io/',
  DATA_PASSWORD: 'TXID_PASSWORD123!',
  PIN_LENGTH: 4,
  DEFAULT_LANGUAGE: 'en',
  PREFIX: 'SIMPLIO',
  LIVECHAT_LICENCE_ID: 13126005,
};
