export const environment = {
  production: false,
  PROGRAM_ID: 'G7zRLf9JT5V1XJVRS2bNM7rKUvkpkw5ESGa52mfTpvGF',
  POOL_ADDRESS: 'CQtV4WPQYUXDHxTXw8K6RJhqiFdndCSBVtj6vtbUoYjD',
  SWAP_WS_URL: 'https://simplio-api-test.azurewebsites.net/ws/notifications',
  SWAP_URL: 'https://simplio-test.azurefd.net/api',
  LANG_URL: 'https://files.simplio.io/beta/',
  SWAP_URL_DEX: 'https://dex-server.simplio.io/api',
  TEMPLATE_REGISTRATION: 'SIO.REGISTRATION',
  TEMPLATE_RESET: 'SIO.PASSWORD-RESET',
  EXPLORER_URL: 'https://files.simplio.io/explorers_fallback_beta.json',
  FEE_URL: 'https://files.simplio.io/feev2.json',
  POLICY_VERSION: '0.1.2',
  CORS_ANYWHERE: 'http://localhost:8080/',
  DATA: 'https://data.simplio.io/',
  DATA_PASSWORD: 'TXID_PASSWORD123!',
  PIN_LENGTH: 4,
  DEFAULT_LANGUAGE: 'en',
  PREFIX: 'SIMPLIO_TEST',
  LIVECHAT_LICENCE_ID: 13126005,
  SUM_SUB_API_URL: 'https://test-api.sumsub.com',
  USER_API: 'https://account-api-pz6mqwi3pa-ew.a.run.app/api/v1',
  SWIPELUX: 'https://api.aws-dev.swipelux.com/api'
};
